[2025-05-03 14:16:06] ERROR [views.post]: ❌ Ошибка при обработке пополнения:
Traceback (most recent call last):
  File "/home/volkan/PycharmProjects/GamesCripth/.venv/lib/python3.11/site-packages/django/shortcuts.py", line 86, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/volkan/PycharmProjects/GamesCripth/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
games.models.Coin.DoesNotExist: Coin matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/volkan/PycharmProjects/GamesCripth/GamesCripth/games/views.py", line 249, in post
    coin = get_object_or_404(Coin, symbol=token_symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/volkan/PycharmProjects/GamesCripth/.venv/lib/python3.11/site-packages/django/shortcuts.py", line 88, in get_object_or_404
    raise Http404(
django.http.response.Http404: No Coin matches the given query.
[2025-05-03 14:16:50] ERROR [views.post]: ❌ Ошибка при обработке пополнения:
Traceback (most recent call last):
  File "/home/volkan/PycharmProjects/GamesCripth/.venv/lib/python3.11/site-packages/django/shortcuts.py", line 86, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/volkan/PycharmProjects/GamesCripth/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
games.models.Coin.DoesNotExist: Coin matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/volkan/PycharmProjects/GamesCripth/GamesCripth/games/views.py", line 249, in post
    coin = get_object_or_404(Coin, symbol=token_symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/volkan/PycharmProjects/GamesCripth/.venv/lib/python3.11/site-packages/django/shortcuts.py", line 88, in get_object_or_404
    raise Http404(
django.http.response.Http404: No Coin matches the given query.
[2025-05-03 14:17:01] ERROR [views.post]: ❌ Ошибка при обработке пополнения:
Traceback (most recent call last):
  File "/home/volkan/PycharmProjects/GamesCripth/.venv/lib/python3.11/site-packages/django/shortcuts.py", line 86, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/volkan/PycharmProjects/GamesCripth/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
games.models.Coin.DoesNotExist: Coin matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/volkan/PycharmProjects/GamesCripth/GamesCripth/games/views.py", line 249, in post
    coin = get_object_or_404(Coin, symbol=token_symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/volkan/PycharmProjects/GamesCripth/.venv/lib/python3.11/site-packages/django/shortcuts.py", line 88, in get_object_or_404
    raise Http404(
django.http.response.Http404: No Coin matches the given query.
[2025-05-03 14:17:03] ERROR [views.post]: ❌ Ошибка при обработке пополнения:
Traceback (most recent call last):
  File "/home/volkan/PycharmProjects/GamesCripth/.venv/lib/python3.11/site-packages/django/shortcuts.py", line 86, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/volkan/PycharmProjects/GamesCripth/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
games.models.Coin.DoesNotExist: Coin matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/volkan/PycharmProjects/GamesCripth/GamesCripth/games/views.py", line 249, in post
    coin = get_object_or_404(Coin, symbol=token_symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/volkan/PycharmProjects/GamesCripth/.venv/lib/python3.11/site-packages/django/shortcuts.py", line 88, in get_object_or_404
    raise Http404(
django.http.response.Http404: No Coin matches the given query.
[2025-05-05 09:21:31] ERROR [views.post]: Error converting amount: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-05-05 09:21:32] ERROR [views.post]: Transaction for coin TON and memo_phrase nwDugItL9495 not found.
[2025-05-05 11:15:45] ERROR [views.process_transaction]: Ошибка при обработке транзакции: module aiohttp has no attribute run
[2025-05-05 11:15:45] ERROR [views.process_transaction]: Ошибка при обработке транзакции: module aiohttp has no attribute run
[2025-05-05 11:15:45] ERROR [views.process_transaction]: Ошибка при обработке транзакции: module aiohttp has no attribute run
[2025-05-05 11:15:45] ERROR [views.process_transaction]: Ошибка при обработке транзакции: module aiohttp has no attribute run
[2025-05-05 11:15:45] ERROR [views.process_transaction]: Ошибка при обработке транзакции: module aiohttp has no attribute run
[2025-05-05 11:15:45] ERROR [views.process_transaction]: Ошибка при обработке транзакции: module aiohttp has no attribute run
[2025-05-05 11:15:45] ERROR [views.process_transaction]: Ошибка при обработке транзакции: module aiohttp has no attribute run
[2025-05-05 11:15:45] ERROR [views.process_transaction]: Ошибка при обработке транзакции: module aiohttp has no attribute run
[2025-05-05 11:15:45] ERROR [views.process_transaction]: Ошибка при обработке транзакции: module aiohttp has no attribute run
